### ISSUE TITLE
Missing dependency in RepositoryDoc.java

### ISSUE THREAD

**Issue by HugoGEORGET** [google-cloudsearch/connector-sdk#19]
Hello,

When running a connector developed from the [Graph traversal sample](https://github.com/gsuitedevs/cloud-search-samples/blob/master/indexing/connector/sdk/graph-traversal/src/main/java/com/google/cloudsearch/samples/GraphTraversalSample.java), I get a NoClassDefFoundError exception on the `com.google.api.client.repackaged.com.google.common.base.Strings` class inside the `getDoc()` method.
More specifically, the missing library is called by the [`addChildId()`](https://github.com/google-cloudsearch/connector-sdk/blob/475b828486fe409b62a78d025abc45d4a61e8cdc/indexing/src/main/java/com/google/enterprise/cloudsearch/sdk/indexing/template/RepositoryDoc.java#L180) method inside the [RepositoryDoc.java](https://github.com/google-cloudsearch/connector-sdk/blob/475b828486fe409b62a78d025abc45d4a61e8cdc/indexing/src/main/java/com/google/enterprise/cloudsearch/sdk/indexing/template/RepositoryDoc.java#L26) class inside the indexing template project.
I already modified the `getIds()` method so let me know if I'm doing something wrong.

Here is the complete stacktrace :

> Exception in thread "TraverserRunner-default-39" com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: com/google/api/client/repackaged/com/google/common/base/Strings
	at com.google.common.util.concurrent.SimpleTimeLimiter.wrapAndThrowExecutionExceptionOrError(SimpleTimeLimiter.java:271)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:154)
	at com.google.enterprise.cloudsearch.sdk.indexing.traverser.ParallelProcessingTraverserWorker$PollAndProcessRunnable.run(ParallelProcessingTraverserWorker.java:153)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NoClassDefFoundError: com/google/api/client/repackaged/com/google/common/base/Strings
	at com.google.enterprise.cloudsearch.sdk.indexing.template.RepositoryDoc$Builder.addChildId(RepositoryDoc.java:180)
	at com.sword.cloudsearch.connectors.sites.Connector$SitesRepository.buildDocumentAndChildren(Connector.java:307)
	at com.sword.cloudsearch.connectors.sites.Connector$SitesRepository.getDoc(Connector.java:253)
	at com.google.enterprise.cloudsearch.sdk.indexing.template.ListingConnector.process(ListingConnector.java:300)
	at com.google.enterprise.cloudsearch.sdk.indexing.traverser.ParallelProcessingTraverserWorker$PollAndProcessRunnable$ProcessingFunction.call(ParallelProcessingTraverserWorker.java:192)
	at com.google.enterprise.cloudsearch.sdk.indexing.traverser.ParallelProcessingTraverserWorker$PollAndProcessRunnable$ProcessingFunction.call(ParallelProcessingTraverserWorker.java:180)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	... 3 more

I tried importing the [corresponding Maven dependency](https://mvnrepository.com/artifact/com.google.api.client/google-api-client-repackaged-com-google-common-base/1.2.3-alpha) but the Strings class doesn't seem to be inside.

Thanks,
Hugo GEORGET

**Comment by wiarlawd** [comment]
It appears that this error occurs if your build gets version 1.26.0 or later of google-http-client.

This was fixed by commit 0097caf.
